name: find_out
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  supabase_flutter: ^2.3.0
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  go_router: ^13.2.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10
  lottie: ^3.1.0
  flutter_tts: ^3.8.5
  image_picker: ^1.0.7
  image: ^4.1.7
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  connectivity_plus: ^6.0.3
  get_it: ^7.6.7

  just_audio: ^0.9.36

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/onboarding/
    - assets/images/auth/
    - assets/images/setup/
    - assets/images/home/
    - assets/images/flags/
    - assets/images/culture/
    - assets/images/grammer/
    - assets/images/reading/
    - assets/images/flash/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800